config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :polls do
    member do
      get 'take'
      post 'vote'
      get 'results'
    end
  end

  root 'polls#index'

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :poll
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :choices
  accepts_nested_attributes_for :choices, :reject_if => :all_blank,
    :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :take, :vote, :results,
                                  :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:take, :vote, :results]

  def take
  end

  def vote
    choice = Choice.where(poll_id: params[:id],
                          name: params[:name]).first
    choice.increment!(:votes)

    redirect_to results_poll_path(id: params[:id])
  end

  def results
  end

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
    2.times { @poll.choices.build }
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title, choices_attributes:
                                   [:id, :name, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-error"
    when "alert" then "alert alert-error"
    end
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VotingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_choice_fields.html.slim
.nested-fields
  = f.input :name
  = link_to_remove_association "remove choice", f

app/views/polls/_form.html.slim
= simple_form_for(@poll) do |f|
  = f.input :title
  #choices
  = f.simple_fields_for :choices do |choice|
    = render 'choice_fields', :f => choice
  .links
    = link_to_add_association 'add choice', f, :choices
  br
  = f.submit class: "btn btn-default"

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.slim
- flash.each do |key, value|
  div[class="#{flash_class(key)}"]
    = value

h1 Listing Polls

-if @polls.any?
  table class="table"
    thead
      tr
        th Title
        th colspan="3"

    tbody
      - @polls.each do |poll|
        tr
          td = poll.title
          td = link_to 'Show', poll
          td = link_to 'Edit', edit_poll_path(poll)
          td = link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' }
-else
  p = "No polls created"

br

= link_to 'New Poll', new_poll_path

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/results.html.slim
p
  strong Title:
  =< @poll.title

= column_chart @poll.choices.group(:name).sum(:votes)

= link_to 'Back', @poll

app/views/polls/show.html.slim
- flash.each do |key, value|
  div[class="#{flash_class(key)}"]
    = value
p
  strong = @poll.title

- if @poll.choices.any?
  - for choice in @poll.choices
    = choice.name
    br

=> link_to 'Edit', edit_poll_path(@poll)
=> link_to 'Link To Take Poll', take_poll_path(@poll)
=> link_to 'View Results', results_poll_path(@poll)
= link_to 'Back', polls_path

app/views/polls/take.html.slim
p
  strong Title:
  = @poll.title

= form_tag("/polls/#{@poll.id}/vote", method: "post") do
  -if @poll.choices.any?
    -@poll.choices.each do |choice|
      div class="radio"
      = label_tag("name_#{choice.name}", "#{choice.name}")
      = radio_button_tag(:name, "#{choice.name}")
  = submit_tag("Vote")

= link_to 'Back', polls_path